Add support for websocket channel(VAIG Async Bot API).
ac-voice-ai/rasa-audiocodes pull request #4
Opened 2020-09-29 14:48 UTC by talaviad

2020-09-29 14:54 UTC, talaviad commented
cc: @orgads
cc: @bivas6
cc:  @yoshigev

2020-09-29 15:02 UTC, orgads requested changes
You don't need to CC us. We're all maintainers, so we get an email immediately when you open the PR.

2020-09-29 15:02 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +                'abcd', cid)   # Should be request.headers.get("Authorization")
And why isn't it? :)

2020-09-29 15:02 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +            return
Add newline

2020-09-29 15:02 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +        message_to_user = {"conversation": self.cid, "activities": self.messages}
self.messages can contain several messages at this point...

I suggest that you create a helper function (maybe post_message?) that either appends to self.messages or sends out on the ws.

2020-09-29 15:08 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +                'abcd', cid)   # Should be request.headers.get("Authorization")
Sorry, will be fixed.

2020-09-29 15:09 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +            return
Ok.

2020-09-29 15:10 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +        message_to_user = {"conversation": self.cid, "activities": self.messages}
A better name might be `add_message`.

2020-09-30 08:32 UTC, orgads commented
Please squash the commits.

2020-09-30 08:32 UTC, bivas6 commented on rasa_audiocodes/audiocodes.py
> +                            "id": str(uuid.uuid4()),
Add id and timestamp in post_message, then you can remove it from the other functions

2020-09-30 08:33 UTC, bivas6 commented on rasa_audiocodes/audiocodes.py
> +            message_to_user = {"conversation": self.cid, "activities": message}
should be an array?

2020-09-30 08:51 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +            message_to_user = {"conversation": self.cid, "activities": message}
Yes, I will change it

2020-09-30 09:04 UTC, orgads requested changes
Please squash all the commits.

2020-09-30 09:04 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +                request.headers.get("Authorization"), cid)
join

2020-09-30 09:04 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +        await self.post_message(new_message)
Can be inlined: `await self.post_message( {"type": "message", "text": text })`.

2020-09-30 09:04 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +    async def post_message(self, message) -> None:
Rename `add_message`.

2020-09-30 09:04 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +        self.messages.append(message)
Needed if `self.ws`?

2020-09-30 09:08 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +                request.headers.get("Authorization"), cid)
What do you mean? join lines 176-177 together?

2020-09-30 09:13 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +        self.messages.append(message)
If the bot responds in rest channel so all the messages will be send altogether in on_activities() using the messages parameter.

2020-09-30 09:17 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +                request.headers.get("Authorization"), cid)
Yes

2020-09-30 09:20 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +        self.messages.append(message)
But in `on_activities` you have:

```python
if conversation.ws is None:
    return response.json(
        {"conversation": cid, "activities": ac_output.messages}
    )

return response.json({})
```

So where do you read messages if ws is enabled?

2020-09-30 09:22 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +        self.messages.append(message)
in add_message

2020-09-30 09:25 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +        self.messages.append(message)
Mabye it will be cleaner to add another class(total 2 for now) so each will take care the way he sends messages?

2020-09-30 09:25 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +        self.messages.append(message)
I lost you. In `add_message` (**this function**) you only _append_ to messages. Where do you read it?

2020-09-30 09:32 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +        self.messages.append(message)
In add_message() I also send the message if the client has ws connection(otherwise I read it in on_activities() and send it as http response)

2020-09-30 09:33 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +        self.messages.append(message)
You send it, but you also append it to `self.messages`, which looks redundant. That's the line I commented on.

2020-09-30 09:37 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +        self.messages.append(message)
I can edit it to:
"if self.ws is not None:
     self.messages.append(message)"
But mabye its will be cleaner to add another class to make the seperation?

2020-09-30 09:38 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +        self.messages.append(message)
Or just `else` :). Anyway, I agree that a separate class is cleaner.

2020-09-30 10:50 UTC, bivas6 commented on rasa_audiocodes/audiocodes.py
> +        async def newClientConnection(request, ws, cid: Text):
new_client_connection

2020-10-01 12:01 UTC, orgads commented on rasa_audiocodes/audiocodes.py
>          )
Please share this part too. Add another function `do_add_message` which will either append or send only.

2020-10-01 13:43 UTC, orgads requested changes
Please move the extra logging to a separate commit/PR.

2020-10-01 13:43 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +logger.addHandler(handler)
Looks unrelated, and should probably not be submitted. Right?

2020-10-01 13:43 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +    def get_basic_urls(self, cid):
Why not inline it?

2020-10-01 13:43 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +                return
raise?

2020-10-01 13:43 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +            websocket_is_on = self.websocket_is_on and conversation.ws is not None
`self.websocket_is_on` needed? Why?

2020-10-01 13:43 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +            conversation = self._get_conversation(request.headers.get("Authorization"), cid)
?

2020-10-01 13:53 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +logger.addHandler(handler)
I am not sure. While the bots run on docker in the background, this is how we can follow what is happening no?

2020-10-01 13:56 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +                return
To raise ConnectionRefusedError instead of the return on line 192?

2020-10-01 13:56 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +            websocket_is_on = self.websocket_is_on and conversation.ws is not None
It comes from the credentials.yml which tells if the bot supports websocket or not.

2020-10-01 13:58 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +            conversation = self._get_conversation(request.headers.get("Authorization"), cid)
Do you ask why I put line 246? if so, just for better logging

2020-10-01 14:05 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +    def get_basic_urls(self, cid):
Do you mean to remove get_basic_urls? but doesn't it nicer like this?

2020-10-12 15:27 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +logger.addHandler(handler)
I will remove it and maybe will be committed separately in the future.

2020-10-12 15:29 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +    def get_basic_urls(self, cid):
I will inline it

2020-10-12 15:30 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +                return
I will raise ConnectionRefusedError

2020-10-12 15:37 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +            conversation = self._get_conversation(request.headers.get("Authorization"), cid)
The assignment to 'conversation' is unnecessary, I will remove it.

2020-10-12 15:40 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +            websocket_is_on = self.websocket_is_on and conversation.ws is not None
'self.websocket_is_on' is unnecessary, I will remove it

2020-10-13 05:32 UTC, orgads requested changes
Last nits.

2020-10-13 05:32 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +
Please move it back to where it was.

2020-10-13 05:32 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +            logger.debug(f"(disconnect) --- At beginning of the function. Conversation: {cid}")
What for?

2020-10-13 05:32 UTC, orgads commented on rasa_audiocodes/audiocodes.py
> +        logger.debug(f"AudiocodesOutput::__init__")
Remove?

2020-10-13 05:52 UTC, talaviad commented on rasa_audiocodes/audiocodes.py
> +            logger.debug(f"(disconnect) --- At beginning of the function. Conversation: {cid}")
I will remove it

2020-10-13 10:42 UTC, orgads approved these changes

2020-10-13 10:42 UTC, merged